CREATE TABLE IF NOT EXISTS users (
 id TEXT PRIMARY KEY NOT NULL, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
 token_hash TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 expires_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS notes (
 id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 body TEXT NOT NULL, created_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS subscriptions (
 user_id TEXT PRIMARY KEY NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 customer_id TEXT NOT NULL UNIQUE, subscription_id TEXT UNIQUE,
 status TEXT NOT NULL DEFAULT 'none', cancel_at_period_end INTEGER NOT NULL DEFAULT 0,
 checkout_key TEXT NOT NULL, checkout_session_id TEXT, revision INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS stripe_events (
 id TEXT PRIMARY KEY NOT NULL, type TEXT NOT NULL, processed_at INTEGER NOT NULL
);
